### PR TITLE
Final Merge from CaretDevelopment ReacType Caret Edition

### PR DESCRIPTION
**Pull request by MadinventorZero**
Final merge from CaretDevelopment

Live Demo Render
Annotations
State Management
CSS Editor
Complete Application Redesign
Successfully Deployed in Windows, macOS, & Linux

### CODE REVIEW

**Review by williamdyoon — APPROVED** [review]
Great Job all

**Review by MadinventorZero — COMMENTED** [review]
LGTM!!!!!! Great Job TEAM!!!!!!!!!! Team Caret forever!!!

**Review by buddhajjigae — APPROVED** [review]
Awesome work

**Review by xkevinpark — APPROVED** [review]
Let's gooooo!!!

**Review by jonocr — APPROVED** [review]
Great Job Team!

**Pull request merged**
